version: '3'
services:
  frontend:
    stdin_open: true
    tty: true
    container_name: frontend-react-admin-typescript
    image: nhuydev1704/base-admin-types_frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules